# Generated by Django 4.2.2 on 2023-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_parents_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parents_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
