# Generated by Django 4.2.2 on 2023-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_room_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
