# Generated by Django 4.2.2 on 2023-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_roomreview_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_image',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
    ]
