# Generated by Django 4.2.2 on 2023-07-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_room_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(null=True, unique_for_date='created_date'),
        ),
    ]
