# Generated by Django 4.2.2 on 2023-07-05 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_roomreview_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
