# Generated by Django 4.2.2 on 2023-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreview',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
