# Generated by Django 4.2.2 on 2023-07-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_roomreview_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='base_image',
        ),
    ]
