# Generated by Django 4.2.2 on 2023-07-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_room_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreview',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.room'),
        ),
    ]
